title: Cláudio Soriano # your name here
logo: "/Foto_perfil/foto_perfil.jpeg" # your photo here

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/claudio-soriano1">LinkedIn</a> |
  <a href="https://zsoriano.github.io/claudiosoriano.github.io/">Portfólio</a> |
  <a href="https://github.com/zSoriano">GitHub</a> |
  <a href="mailto:claudio.cordeiro@ufv.br">E-mail</a>
  </p>
  
  <p align="center">
   Olá, bem vindx ao meu portfólio de projetos.
   Aqui, apresento minhas habilidades na resolução de problemas de negócios por meio de Análise de Dados, 
   Estatística e Machine Learning.
   
   </p>
   <p align="center">
   <a href="#projetos-ml">Projetos de Machine Learning</a> <br>
   <a href="#projetos-analise">؜؜Projetos de Análise de Dados</a> <br>
   <a href="#projetos-estatistica">Estatística para Análise de Dados</a> <br>
   <a href="#ml-processamento">Processamento de Dados para ML</a> <br>
   <a href="#projetos-estimadores">Estimadores em Machine Learning</a>
   </p> 
   </p>
   <p align="center">
   <br><br>
   </p>
theme: jekyll-theme-minimal
